"""Carina/Aiva capability node catalog (P0-P2 + owner-gated Nice)."""

from __future__ import annotations

from keprix.product_sidecar.types import CapabilityNode, NodeStatus, RiskClass


def _node(
    key: str,
    *,
    title: str,
    domain: str,
    risk: RiskClass,
    status: NodeStatus,
    soft_wall: bool = False,
    grants: tuple[str, ...] = (),
    entitlements: tuple[str, ...] = (),
    sync: bool = True,
    idempotent: bool = False,
    aiva_sku_ok: bool = True,
    carina_admin_only: bool = False,
    guidance: str = "",
    product: str = "carina",
) -> CapabilityNode:
    return CapabilityNode(
        key=key,
        version="1.0.0",
        title=title,
        product=product,
        domain=domain,
        risk=risk,
        status=status,
        required_grants=grants or (f"node:{key}",),
        entitlements=entitlements,
        soft_wall=soft_wall,
        sync=sync,
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        timeout_seconds=60 if not sync else 30,
        budget_units=2 if risk in {RiskClass.OUTBOUND, RiskClass.MUTATE} else 1,
        idempotent=idempotent,
        operator_guidance=guidance,
        aiva_sku_ok=aiva_sku_ok,
        carina_admin_only=carina_admin_only,
    )


def build_carina_nodes() -> dict[str, CapabilityNode]:
    """Full advertised catalog for Carina (shared brain)."""
    nodes = [
        _node(
            "agent.run",
            title="Agent turn",
            domain="agent",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            grants=("node:agent.run", "agent:run"),
            guidance="Maps to legacy POST /carina/agent/run",
        ),
        _node(
            "agent.interrupt",
            title="Interrupt agent turn",
            domain="agent",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            grants=("node:agent.interrupt", "agent:run"),
            idempotent=True,
        ),
        _node(
            "soft_wall.request",
            title="Request Soft Wall approval",
            domain="soft_wall",
            risk=RiskClass.PROPOSE,
            status=NodeStatus.LIVE,
            soft_wall=False,
            grants=("node:soft_wall.request", "soft_wall:request"),
            idempotent=True,
        ),
        _node(
            "soft_wall.status",
            title="Soft Wall approval status",
            domain="soft_wall",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:soft_wall.status", "soft_wall:read"),
        ),
        _node(
            "crm.search",
            title="CRM search (projected)",
            domain="crm",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:crm.search", "crm:read"),
        ),
        _node(
            "crm.propose",
            title="CRM propose change",
            domain="crm",
            risk=RiskClass.PROPOSE,
            status=NodeStatus.LIVE,
            soft_wall=True,
            grants=("node:crm.propose", "crm:propose"),
            idempotent=True,
        ),
        _node(
            "crm.enroll",
            title="CRM list enroll Soft Wall",
            domain="crm",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.LIVE,
            soft_wall=True,
            grants=("node:crm.enroll", "crm:enroll"),
            idempotent=True,
        ),
        _node(
            "crm.pipeline.read",
            title="CRM pipeline read",
            domain="crm",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:crm.pipeline.read", "crm:read"),
        ),
        _node(
            "crm.analytics.summary",
            title="CRM analytics summary",
            domain="crm",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:crm.analytics.summary", "crm:read"),
        ),
        _node(
            "discovery.jobs.create",
            title="Start discovery job",
            domain="discovery",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            soft_wall=True,
            sync=False,
            grants=("node:discovery.jobs.create", "discovery:write"),
            idempotent=True,
        ),
        _node(
            "outreach.outbox.enqueue",
            title="Enqueue outreach outbox",
            domain="outreach",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.LIVE,
            soft_wall=True,
            grants=("node:outreach.outbox.enqueue", "outreach:write"),
            idempotent=True,
        ),
        _node(
            "vical.booking.offer",
            title="Create booking offer",
            domain="vical",
            risk=RiskClass.PROPOSE,
            status=NodeStatus.LIVE,
            soft_wall=True,
            grants=("node:vical.booking.offer", "vical:write"),
            idempotent=True,
        ),
        _node(
            "booking.status",
            title="Booking status",
            domain="vical",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:booking.status", "vical:read"),
        ),
        _node(
            "scout.hooks.emit",
            title="Emit Scout governance hook",
            domain="scout",
            risk=RiskClass.PROPOSE,
            status=NodeStatus.LIVE,
            grants=("node:scout.hooks.emit", "scout:hook"),
            guidance="Scout remains the governance console; this is hooks only",
        ),
        _node(
            "memory.get",
            title="Workspace memory get",
            domain="memory",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:memory.get", "memory:read"),
        ),
        _node(
            "memory.put",
            title="Workspace memory put",
            domain="memory",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            grants=("node:memory.put", "memory:write"),
            idempotent=True,
        ),
        _node(
            "rag.search",
            title="RAG search",
            domain="rag",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:rag.search", "rag:read"),
        ),
        _node(
            "playbook.start",
            title="Start playbook",
            domain="playbook",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            soft_wall=True,
            sync=False,
            grants=("node:playbook.start", "playbook:run"),
            idempotent=True,
        ),
        _node(
            "playbook.status",
            title="Playbook run status",
            domain="playbook",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:playbook.status", "playbook:read"),
        ),
        _node(
            "jobs.create",
            title="Create async job",
            domain="jobs",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            sync=False,
            grants=("node:jobs.create", "jobs:write"),
            idempotent=True,
        ),
        _node(
            "jobs.cancel",
            title="Cancel async job",
            domain="jobs",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            grants=("node:jobs.cancel", "jobs:write"),
            idempotent=True,
        ),
        _node(
            "channels.notify",
            title="Operator channel notify",
            domain="channels",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.LIVE,
            soft_wall=True,
            grants=("node:channels.notify", "channels:notify"),
            idempotent=True,
        ),
        _node(
            "data.datasets.list",
            title="List datasets",
            domain="data",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:data.datasets.list", "data:read"),
        ),
        _node(
            "data.jobs.create",
            title="Create data plane job",
            domain="data",
            risk=RiskClass.MUTATE,
            status=NodeStatus.LIVE,
            soft_wall=True,
            sync=False,
            grants=("node:data.jobs.create", "data:write"),
            idempotent=True,
        ),
        _node(
            "data.export",
            title="Export data Soft Wall",
            domain="data",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.LIVE,
            soft_wall=True,
            grants=("node:data.export", "data:export"),
            idempotent=True,
        ),
        # Owner-gated Nice (honest not_configured)
        _node(
            "crm.enrich.licensed",
            title="Licensed CRM enrich",
            domain="crm",
            risk=RiskClass.HIGH_RISK,
            status=NodeStatus.NOT_CONFIGURED,
            soft_wall=True,
            grants=("node:crm.enrich.licensed", "crm:enrich"),
            guidance="Requires owner-cleared enrich credentials",
        ),
        _node(
            "channels.whatsapp.send",
            title="WhatsApp send",
            domain="channels",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.NOT_CONFIGURED,
            soft_wall=True,
            grants=("node:channels.whatsapp.send", "channels:wa"),
            aiva_sku_ok=True,
            guidance="Owner-gated live WA keys",
        ),
        _node(
            "channels.sms.send",
            title="SMS send",
            domain="channels",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.NOT_CONFIGURED,
            soft_wall=True,
            grants=("node:channels.sms.send", "channels:sms"),
            guidance="Owner-gated live SMS keys",
        ),
        _node(
            "social.oauth.publish",
            title="Social OAuth publish",
            domain="channels",
            risk=RiskClass.OUTBOUND,
            status=NodeStatus.NOT_CONFIGURED,
            soft_wall=True,
            grants=("node:social.oauth.publish", "social:publish"),
            carina_admin_only=False,
            guidance="Owner-gated social OAuth",
        ),
        _node(
            "ops.engine.probe",
            title="Primary invoke path probe",
            domain="ops",
            risk=RiskClass.READ,
            status=NodeStatus.LIVE,
            grants=("node:ops.engine.probe", "ops:read"),
            aiva_sku_ok=False,
            carina_admin_only=True,
            guidance="OPS honesty: not a health ping alone",
        ),
    ]
    return {n.key: n for n in nodes}


def build_aiva_wrapper_nodes(carina_nodes: dict[str, CapabilityNode]) -> dict[str, CapabilityNode]:
    """Aiva reuses Carina node implementations; metadata product=aiva only."""
    wrapped: dict[str, CapabilityNode] = {}
    for key, node in carina_nodes.items():
        if node.carina_admin_only:
            continue
        wrapped[key] = CapabilityNode(
            key=node.key,
            version=node.version,
            title=node.title,
            product="aiva",
            domain=node.domain,
            risk=node.risk,
            status=node.status,
            required_grants=node.required_grants,
            entitlements=node.entitlements or ("aiva.worker",),
            soft_wall=node.soft_wall,
            sync=node.sync,
            input_schema=node.input_schema,
            output_schema=node.output_schema,
            timeout_seconds=node.timeout_seconds,
            budget_units=node.budget_units,
            idempotent=node.idempotent,
            operator_guidance=node.operator_guidance,
            aiva_sku_ok=node.aiva_sku_ok,
            carina_admin_only=False,
        )
    return wrapped
