"""First-run environment discovery wizard."""

from __future__ import annotations

import asyncio
import os
import secrets
import socket
import subprocess
from pathlib import Path

import httpx

from keprix.config.paths import generated_env_file

PROVIDER_ENDPOINTS: list[tuple[str, str, str]] = [
    ("DEEPSEEK", "KEPRIX_DEEPSEEK_API_KEY", "https://api.deepseek.com/"),
    ("GROQ", "KEPRIX_GROQ_API_KEY", "https://api.groq.com/"),
    ("OPENAI", "OPENAI_API_KEY", "https://api.openai.com/"),
    ("ANTHROPIC", "ANTHROPIC_API_KEY", "https://api.anthropic.com/"),
    ("OPENROUTER", "OPENROUTER_API_KEY", "https://openrouter.ai/"),
]


async def discover_environment() -> dict[str, str]:
    """Probe the environment and return env vars that should be set."""
    config: dict[str, str] = {}

    print("keprix - Environment Discovery")
    print("This wizard runs once to configure keprix for your system.")
    print("")

    try:
        with open("/proc/meminfo") as handle:
            for line in handle:
                if line.startswith("MemTotal:"):
                    total_kb = int(line.split()[1])
                    total_mb = total_kb // 1024
                    redis_limit = max(128, total_mb // 4)
                    config["KEPRIX_REDIS_MAXMEMORY"] = f"{redis_limit}mb"
                    print(f"System RAM: {total_mb}MB - Redis will use up to {redis_limit}MB")
                    break
    except Exception:
        config["KEPRIX_REDIS_MAXMEMORY"] = "512mb"

    for port in range(8000, 8100):
        with socket.socket() as sock:
            if sock.connect_ex(("localhost", port)) != 0:
                config["KEPRIX_API_PORT"] = str(port)
                print(f"API server will use port {port}")
                break

    reachable: list[str] = []
    async with httpx.AsyncClient(timeout=5.0) as client:
        for name, env_key, url in PROVIDER_ENDPOINTS:
            key = os.environ.get(env_key, "")
            if not key:
                print(f"  {name}: no key set (skipping)")
                continue
            try:
                response = await client.head(url)
                print(f"  {name}: reachable (HTTP {response.status_code})")
                reachable.append(name.lower())
            except Exception:
                print(f"  {name}: unreachable (network error)")

    if reachable:
        config["KEPRIX_LLM_PROVIDER_PRIORITY"] = ",".join(reachable)
        config["KEPRIX_DEFAULT_LLM_PROVIDER"] = reachable[0]
        print(f"LLM provider priority: {', '.join(reachable)}")
    else:
        print("WARNING: No LLM providers reachable. Add at least one API key.")

    try:
        subprocess.run(["docker", "info"], capture_output=True, check=True, timeout=10)
        config["KEPRIX_SANDBOX_ENABLED"] = "true"
        config["KEPRIX_SANDBOX_DRIVER"] = "docker"
        print("Docker: available - keprix Agent sandbox enabled")
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        config["KEPRIX_SANDBOX_ENABLED"] = "false"
        print("Docker: not available - keprix Agent sandbox disabled")
        print("  To enable: install Docker and re-run: keprix configure")

    if not os.environ.get("KEPRIX_REDIS_PASSWORD"):
        password = secrets.token_urlsafe(32)
        config["KEPRIX_REDIS_PASSWORD"] = password
        config["KEPRIX_REDIS_URL"] = f"redis://:{password}@redis:6379"
        print("Redis: generated secure password")

    out_path = generated_env_file()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as handle:
        handle.write("# Auto-generated by keprix environment discovery\n")
        handle.write("# Edit this file or run: keprix configure\n\n")
        for key, value in sorted(config.items()):
            handle.write(f"{key}={value}\n")

    print(f"\nConfiguration written to: {out_path}")
    print("Start the agent with: keprix gateway start")
    return config


def run_discover_environment() -> int:
    asyncio.run(discover_environment())
    return 0
