"""Export coding context bundles for web chat fallbacks."""

from __future__ import annotations

from dataclasses import dataclass

from keprix.coding.context_loader import LoadedContext
from keprix.coding.repo_map import RepoMap
from keprix.security.redactor import get_redactor


@dataclass
class WebChatBundle:
    title: str
    markdown: str
    json_summary: dict

    def clipboard_text(self) -> str:
        return self.markdown


def export_web_chat_bundle(
    *,
    context: LoadedContext,
    repo_map: RepoMap | None = None,
    patch: str = "",
    test_summary: str = "",
    title: str = "Keprix coding session",
) -> WebChatBundle:
    redactor = get_redactor()
    sections: list[str] = [f"# {title}", ""]
    if context.coding_request:
        sections.extend(["## Request", redactor.redact(context.coding_request), ""])
    if repo_map:
        sections.extend(["## Repo map", "```text", repo_map.compact_text(), "```", ""])
    if context.artifacts:
        sections.append("## Context artifacts")
        for artifact in context.artifacts:
            sections.append(f"- **{artifact.kind}** `{artifact.source}`: {artifact.summary}")
        sections.append("")
    if patch:
        sections.extend(["## Proposed patch", "```diff", redactor.redact(patch), "```", ""])
    if test_summary:
        sections.extend(["## Test summary", "```text", redactor.redact(test_summary[:4000]), "```", ""])
    sections.append("## Notes")
    sections.append("- Generated by Keprix coding export for web chat fallback.")
    sections.append("- Secrets are redacted; verify paths before applying changes.")

    markdown = "\n".join(sections).strip() + "\n"
    json_summary = {
        "title": title,
        "coding_request": context.coding_request,
        "artifact_count": len(context.artifacts),
        "repo_root": repo_map.root if repo_map else None,
        "has_patch": bool(patch),
        "has_tests": bool(test_summary),
    }
    return WebChatBundle(title=title, markdown=markdown, json_summary=json_summary)
