"""Opportunity Engine playbooks."""

from keprix.opportunity.playbooks.asset_factory import (
    AssetFactoryInput,
    MissingOfferDocError,
    UnsupportedClaimError,
    build_all_assets,
    resolve_offer_context,
    run_asset_factory_playbook,
    validate_asset_claims,
)
from keprix.opportunity.playbooks.competitor_intelligence import (
    CompetitorIntelligenceInput,
    CompetitorRecord,
    is_private_source,
    merge_duplicate_competitors,
    run_competitor_intelligence_playbook,
    validate_competitor_citations,
)
from keprix.opportunity.playbooks.icp_builder import (
    IcpBuilderInput,
    build_icp_profiles,
    run_icp_builder_playbook,
    validate_no_predatory_targeting,
)
from keprix.opportunity.playbooks.market_demand import (
    DemandPocket,
    MarketDemandInput,
    compute_overall_demand_score,
    run_market_demand_playbook,
)
from keprix.opportunity.playbooks.offer_builder import (
    OfferBuilderInput,
    build_offer_record,
    build_pricing_hypotheses,
    detect_regulated_industry,
    run_offer_builder_playbook,
    validate_no_false_proof,
    validate_no_guaranteed_income,
)
from keprix.opportunity.playbooks.pain_mining import (
    MarketPain,
    PainMiningInput,
    rank_pains,
    run_pain_mining_playbook,
    sanitize_quote,
    validate_pain_citations,
)
from keprix.opportunity.playbooks.offer_doc_generator import (
    CanonicalOfferDoc,
    build_canonical_offer_from_meta,
    load_canonical_offer_doc,
    run_offer_doc_generator_playbook,
    store_opportunity_scoped_memory,
)
from keprix.opportunity.playbooks.growth_loop import (
    GrowthLoopInput,
    GrowthLoopResult,
    rank_experiments,
    run_growth_loop_playbook,
    validate_growth_guardrails,
)
from keprix.opportunity.playbooks.launch_orchestrator import (
    LaunchBlockedError,
    LaunchPlanResult,
    run_launch_plan,
    run_launch_orchestrator_playbook,
)
from keprix.opportunity.playbooks.validation_score import (
    ValidationBlockedError,
    ValidationScoreInput,
    ValidationResult,
    can_proceed_to_assets,
    compute_validation_result,
    compute_weighted_overall,
    recommendation_from_score,
    run_validation_score_playbook,
    should_block_asset_generation,
)

__all__ = [
    "AssetFactoryInput",
    "CanonicalOfferDoc",
    "CompetitorIntelligenceInput",
    "CompetitorRecord",
    "GrowthLoopInput",
    "GrowthLoopResult",
    "IcpBuilderInput",
    "MarketDemandInput",
    "MarketPain",
    "OfferBuilderInput",
    "PainMiningInput",
    "LaunchBlockedError",
    "LaunchPlanResult",
    "MissingOfferDocError",
    "UnsupportedClaimError",
    "ValidationBlockedError",
    "ValidationResult",
    "ValidationScoreInput",
    "build_all_assets",
    "build_canonical_offer_from_meta",
    "build_icp_profiles",
    "build_offer_record",
    "build_pricing_hypotheses",
    "can_proceed_to_assets",
    "compute_overall_demand_score",
    "compute_validation_result",
    "compute_weighted_overall",
    "detect_regulated_industry",
    "is_private_source",
    "load_canonical_offer_doc",
    "merge_duplicate_competitors",
    "rank_pains",
    "rank_experiments",
    "recommendation_from_score",
    "resolve_offer_context",
    "run_asset_factory_playbook",
    "run_competitor_intelligence_playbook",
    "run_icp_builder_playbook",
    "run_market_demand_playbook",
    "run_growth_loop_playbook",
    "run_launch_orchestrator_playbook",
    "run_launch_plan",
    "run_offer_doc_generator_playbook",
    "run_offer_builder_playbook",
    "run_pain_mining_playbook",
    "run_validation_score_playbook",
    "sanitize_quote",
    "should_block_asset_generation",
    "store_opportunity_scoped_memory",
    "validate_asset_claims",
    "validate_competitor_citations",
    "validate_growth_guardrails",
    "validate_no_false_proof",
    "validate_no_guaranteed_income",
    "validate_no_predatory_targeting",
    "validate_pain_citations",
]
