"""PSPP / SPSS syntax generation."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from keprix.research_workspace.datasets.codebook import Codebook
from keprix.research_workspace.stats.pspp.errors import PSPPPathNotAllowedError, PSPPUnsafeFragmentError
from keprix.research_workspace.stats.pspp.procedures import normalize_procedure
from keprix.research_workspace.stats.pspp.templates import PROCEDURE_TEMPLATES

_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_FORBIDDEN_FRAGMENT_RE = re.compile(r"[;`|$&<>]")


def sanitize_identifier(name: str) -> str:
    if not _IDENTIFIER_RE.match(name):
        raise PSPPUnsafeFragmentError(f"Unsafe variable identifier: {name}")
    return name


def sanitize_path(path: Path, *, workspace_root: Path, approve_external: bool = False) -> Path:
    resolved = path.expanduser().resolve()
    workspace = workspace_root.resolve()
    inside = resolved == workspace or workspace in resolved.parents
    if not inside and not approve_external:
        raise PSPPPathNotAllowedError(
            "External data paths require explicit approval before PSPP syntax generation"
        )
    return resolved


def _format_var_list(value: str | list[str]) -> str:
    if isinstance(value, str):
        items = [part.strip() for part in value.replace(",", " ").split() if part.strip()]
    else:
        items = [str(item).strip() for item in value]
    return " ".join(sanitize_identifier(item) for item in items)


def generate_data_list(codebook: Codebook, data_path: Path) -> list[str]:
    names = " ".join(sanitize_identifier(variable.name) for variable in codebook.variables)
    return [
        "* Data import generated by keprix.",
        f"GET FILE='{data_path.as_posix()}'.",
        "DATASET NAME research.",
        f"* DATA LIST free / {names}.",
    ]


def generate_dictionary_blocks(codebook: Codebook) -> list[str]:
    lines: list[str] = []
    label_pairs: list[str] = []
    for variable in codebook.variables:
        name = sanitize_identifier(variable.name)
        if variable.label:
            label_pairs.append(f"{name} '{_escape_quote(variable.label)}'")
        if variable.value_labels:
            pairs = " ".join(
                f"{key} '{_escape_quote(label)}'" for key, label in variable.value_labels.items()
            )
            lines.append(f"VALUE LABELS {name} {pairs}.")
        if variable.missing_codes:
            codes = " ".join(variable.missing_codes)
            lines.append(f"MISSING VALUES {name} ({codes}).")
    if label_pairs:
        lines.insert(0, "VARIABLE LABELS " + " ".join(label_pairs) + ".")
    return lines


def generate_procedure_block(procedure_payload: dict[str, Any]) -> str:
    spec, params = normalize_procedure(procedure_payload)
    template = PROCEDURE_TEMPLATES[spec.syntax_keyword]
    formatted: dict[str, str] = {}
    for key, value in params.items():
        if key in {"variables", "independents"}:
            formatted[key] = _format_var_list(value)
        elif isinstance(value, list):
            formatted[key] = _format_var_list(value)
        else:
            formatted[key] = sanitize_identifier(str(value))
    if "variables" in spec.required_params and "variables" not in formatted:
        formatted["variables"] = _format_var_list(params["variables"])
    if "independents" in spec.required_params:
        formatted["independents"] = _format_var_list(params["independents"])
    try:
        line = template.format(**formatted)
    except KeyError as exc:
        raise ValueError(f"Missing template field for {spec.name}: {exc}") from exc
    if _FORBIDDEN_FRAGMENT_RE.search(line):
        raise PSPPUnsafeFragmentError("Generated syntax contains forbidden shell fragments")
    return line


def generate_analysis_syntax(
    *,
    codebook: Codebook,
    data_path: Path,
    workspace_root: Path,
    procedures: list[dict[str, Any]] | None = None,
    approve_external_paths: bool = False,
) -> str:
    safe_path = sanitize_path(data_path, workspace_root=workspace_root, approve_external=approve_external_paths)
    lines = generate_data_list(codebook, safe_path)
    lines.extend(generate_dictionary_blocks(codebook))
    lines.append("EXECUTE.")
    for procedure in procedures or [{"type": "frequencies", "variables": [v.name for v in codebook.variables[:3]]}]:
        lines.append(generate_procedure_block(procedure))
    lines.append("EXECUTE.")
    return "\n".join(lines) + "\n"


def _escape_quote(text: str) -> str:
    return text.replace("'", "''")
