"""PSPP syntax templates."""

from __future__ import annotations

FREQUENCIES_TEMPLATE = "FREQUENCIES VARIABLES={variables}."
DESCRIPTIVES_TEMPLATE = "DESCRIPTIVES VARIABLES={variables}."
CROSSTABS_TEMPLATE = "CROSSTABS /TABLES={row} BY {column}."
T_TEST_TEMPLATE = "T-TEST GROUPS={groups} /VARIABLES={dependent}."
ONEWAY_TEMPLATE = "ONEWAY {dependent} BY {factor}."
CORRELATIONS_TEMPLATE = "CORRELATIONS /VARIABLES={variables}."
REGRESSION_TEMPLATE = "REGRESSION /DEPENDENT={dependent} /METHOD=ENTER {independents}."
LOGISTIC_REGRESSION_TEMPLATE = (
    "LOGISTIC REGRESSION VARIABLES={dependent} {independents} /METHOD=ENTER {independents}."
)

PROCEDURE_TEMPLATES = {
    "FREQUENCIES": FREQUENCIES_TEMPLATE,
    "DESCRIPTIVES": DESCRIPTIVES_TEMPLATE,
    "CROSSTABS": CROSSTABS_TEMPLATE,
    "T-TEST": T_TEST_TEMPLATE,
    "ONEWAY": ONEWAY_TEMPLATE,
    "CORRELATIONS": CORRELATIONS_TEMPLATE,
    "REGRESSION": REGRESSION_TEMPLATE,
    "LOGISTIC REGRESSION": LOGISTIC_REGRESSION_TEMPLATE,
}
