"""Incident log and public post generation."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from keprix.support.store import get_support_store


def create_incident(*, title: str, severity: str, summary: str) -> dict[str, Any]:
    incident = {
        "id": str(uuid.uuid4()),
        "title": title,
        "severity": severity,
        "status": "investigating",
        "summary": summary,
        "started_at": datetime.now(timezone.utc).isoformat(),
        "resolved_at": None,
        "updates": [],
        "public_post": None,
    }
    return get_support_store().save_incident(incident)


def add_incident_update(
    incident_id: str,
    *,
    message: str,
    status: str | None = None,
) -> dict[str, Any] | None:
    store = get_support_store()
    incident = store.get_incident(incident_id)
    if incident is None:
        return None
    update = {
        "at": datetime.now(timezone.utc).isoformat(),
        "message": message,
        "status": status,
    }
    incident["updates"].append(update)
    if status:
        incident["status"] = status
        if status == "resolved":
            incident["resolved_at"] = update["at"]
    return store.update_incident(incident_id, incident)


def generate_public_incident_post(incident: dict[str, Any]) -> str:
    lines = [
        f"# Incident: {incident['title']}",
        "",
        f"**Severity:** {incident['severity']}",
        f"**Status:** {incident['status']}",
        f"**Started:** {incident['started_at']}",
        "",
        "## Summary",
        incident["summary"],
        "",
        "## Timeline",
    ]
    for update in incident.get("updates") or []:
        stamp = update.get("at", "")
        status = update.get("status")
        suffix = f" ({status})" if status else ""
        lines.append(f"- {stamp}{suffix}: {update.get('message', '')}")
    if incident.get("resolved_at"):
        lines.extend(["", f"**Resolved:** {incident['resolved_at']}"])
    lines.extend(
        [
            "",
            "_This post was generated by Keprix incident communications. "
            "Share only after review; do not include customer data or secrets._",
        ]
    )
    return "\n".join(lines)
