"""Scaffold new agent app folders from CLI templates."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from keprix.agent_apps.registry import get_agent_app_registry

_SLUG_RE = re.compile(r"[^a-z0-9-]+")


def slugify_name(name: str) -> str:
    slug = _SLUG_RE.sub("-", name.strip().lower()).strip("-")
    if not slug:
        raise ValueError("App name must contain at least one letter or digit")
    return slug


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _agent_template_files(slug: str, display_name: str) -> dict[str, str]:
    title = display_name or slug.replace("-", " ").title()
    return {
        "agent.yaml": f"""name: {slug}
version: 1.0.0
display_name: {title}
description: Agent app scaffold generated by `keprix agent-app create`.
category: custom
runtime: agent
required_env:
  - KEPRIX_DEFAULT_PROVIDER
required_permissions:
  - network
tools:
  - tools/sample.yaml
inputs:
  - id: topic
    label: Topic
    type: text
    required: true
    placeholder: What should the agent focus on?
outputs:
  - id: markdown
    type: markdown
eval_suite: evals/basic.yaml
""",
        "instructions.md": f"""You are **{title}**, a Keprix agent app.

Use the sample tool when helpful. Respond with concise markdown the operator can paste into notes.
""",
        "prompt_template.md": """Summarise the following topic for a busy operator:

Topic: {{topic}}
""",
        "tools/sample.yaml": """name: sample
description: Return a short acknowledgement for the given topic
risk: low
approval_required: false
""",
        "evals/basic.yaml": """cases:
  - name: responds with topic
    input:
      topic: standup
    expect_contains: standup
""",
        "README.md": f"""# {title}

Generated by `keprix agent-app create`. Edit `agent.yaml`, then:

```bash
keprix agent-app validate .
keprix agent-app run . --input "Hello"
keprix agent-app bundle . -o {slug}.zip
```
""",
    }


def _python_template_files(slug: str, display_name: str) -> dict[str, str]:
    title = display_name or slug.replace("-", " ").title()
    module = slug.replace("-", "_")
    return {
        "agent.yaml": f"""name: {slug}
version: 1.0.0
display_name: {title}
description: Python agent app scaffold generated by `keprix agent-app create`.
category: custom
runtime: python
entrypoint: agents.main:run
tools:
  - tools/greet.yaml
required_env: []
required_permissions:
  - network
eval_suite: evals/basic.yaml
inputs:
  - id: name
    label: Your name
    type: text
    required: false
    default: world
outputs:
  - id: text
    type: text
""",
        "agents/main.py": f'''"""Entrypoint for {slug}."""


def run(inputs: dict | None = None, **_kwargs) -> dict:
    payload = inputs or {{}}
    name = str(payload.get("name") or "world")
    return {{"text": f"Hello, {{name}} from {slug}!"}}
''',
        "tools/greet.yaml": """name: greet
description: Return a greeting for the provided name
risk: low
approval_required: false
""",
        "evals/basic.yaml": """cases:
  - name: greets user
    input: world
    expect_contains: Hello
""",
        "instructions.md": f"""You are a Python-backed sample app for {title}.
""",
        "README.md": f"""# {title}

Python runtime app. Validate and run locally:

```bash
keprix agent-app validate .
keprix agent-app run . --input "keprix"
```
""",
    }


def create_agent_app(
    dest: Path,
    name: str,
    *,
    template: str = "agent",
    force: bool = False,
) -> dict[str, Any]:
    slug = slugify_name(name)
    root = dest.expanduser().resolve()
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Destination is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)

    if template == "python":
        files = _python_template_files(slug, name.strip())
    elif template == "agent":
        files = _agent_template_files(slug, name.strip())
    else:
        raise ValueError(f"Unknown template: {template}")

    for relative, content in files.items():
        _write(root / relative, content)

    validation = get_agent_app_registry().validate_only(root)
    return {
        "path": str(root),
        "name": slug,
        "template": template,
        "valid": bool(validation.get("valid")),
        "validation": validation,
    }
