#!/usr/bin/env python3
"""Build scoped multi-skin CSS and manifest from planning UI CSS packs."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "planning" / "prompts" / "UI" / "css"
OUT_CSS = ROOT / "frontend" / "public" / "themes" / "skins.css"
OUT_MANIFEST = ROOT / "frontend" / "src" / "theme" / "skin-manifest.json"
PREFIX = "01-multi-theme-switching-"


def parse_block(content: str, selector: str) -> str | None:
    pattern = rf"{re.escape(selector)}\s*\{{([^}}]*)\}}"
    match = re.search(pattern, content, re.DOTALL)
    if not match:
        return None
    return match.group(1).strip()


def parse_vars(block: str) -> dict[str, str]:
    vars_map: dict[str, str] = {}
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("--"):
            continue
        if ":" not in line:
            continue
        name, value = line.split(":", 1)
        vars_map[name.strip()] = value.strip().rstrip(";").strip()
    return vars_map


def label_from_id(skin_id: str) -> str:
    return skin_id.replace("-", " ").title()


def main() -> None:
    skins: list[dict[str, str]] = []
    css_parts: list[str] = [
        "/* Auto-generated by scripts/build-theme-skins.py. Do not edit by hand. */",
        "",
    ]

    for path in sorted(SOURCE_DIR.glob(f"{PREFIX}*.css")):
        if path.name.endswith(".csss"):
            continue
        skin_id = path.stem[len(PREFIX) :]
        content = path.read_text(encoding="utf-8")
        light_block = parse_block(content, ":root")
        dark_block = parse_block(content, ".dark")
        if not light_block:
            continue

        light_vars = parse_vars(light_block)
        css_parts.append(f'html[data-skin="{skin_id}"] {{')
        css_parts.append(f"  {light_block}")
        css_parts.append("}")
        css_parts.append("")

        if dark_block:
            css_parts.append(f'html.dark[data-skin="{skin_id}"] {{')
            css_parts.append(f"  {dark_block}")
            css_parts.append("}")
            css_parts.append("")

        skins.append(
            {
                "id": skin_id,
                "label": label_from_id(skin_id),
                "primary": light_vars.get("--primary", "#7c3aed"),
                "background": light_vars.get("--background", "#0f172a"),
                "foreground": light_vars.get("--foreground", "#f8fafc"),
            }
        )

    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    OUT_CSS.write_text("\n".join(css_parts) + "\n", encoding="utf-8")
    OUT_MANIFEST.write_text(json.dumps({"skins": skins}, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(skins)} skins to {OUT_CSS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
