#!/usr/bin/env python3
"""Generate auto-maintained MkDocs reference pages for Keprix."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
ENV_EXAMPLE = ROOT / ".env.example"
CHANGELOG = ROOT / "CHANGELOG.md"
LICENSE = ROOT / "LICENSE"


def _banner(title: str) -> str:
    return (
        f"# {title}\n\n"
        "<!-- AUTO-GENERATED by scripts/generate_doc_pages.py; do not edit by hand. -->\n\n"
    )


def _is_section_header(text: str) -> bool:
    """True for titled section lines, not inline Optional: VAR= notes."""
    if not text or text.startswith("Copy to"):
        return False
    if text.lower().startswith("optional:"):
        return False
    if text.lower().startswith("prefer "):
        return False
    if text.lower().startswith("generate:"):
        return False
    if text.lower().startswith("required:"):
        return False
    if text.lower().startswith("required for"):
        return False
    if text.lower().endswith("generate with:"):
        return False
    if text.lower().startswith("nvidia:") or text.lower().startswith("amd:"):
        return False
    if text.lower().startswith("public https"):
        return False
    if text.lower().startswith("bash ") or text.lower().startswith("start "):
        return False
    # Assignment-like comment lines are not section titles.
    if re.match(r"^[A-Z][A-Z0-9_]*=", text):
        return False
    if "=" in text and not text.endswith(":"):
        return False
    # Short title-like headers (LLM Providers, Auth and Sessions, ...).
    if len(text) <= 80 and (text.endswith(":") or " " in text or text.isalpha()):
        if text.endswith(":"):
            return True
        # Title Case / short labels without trailing period clutter.
        if not text.endswith(".") and len(text.split()) <= 8:
            return True
    return False


def parse_env_example(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    section = "General"
    pending_comments: list[str] = []

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("# Copy to"):
            continue
        if line.startswith("# =="):
            pending_comments.clear()
            continue
        if line.startswith("#"):
            text = line.lstrip("#").strip()
            if not text:
                continue
            if _is_section_header(text):
                section = text.rstrip(":").strip()
                pending_comments.clear()
                continue
            pending_comments.append(text)
            continue
        if "=" not in line:
            pending_comments.clear()
            continue
        name, _, value = line.partition("=")
        name = name.strip()
        value = value.strip()
        # Prefer the last comment immediately above the assignment.
        description = pending_comments[-1] if pending_comments else section
        pending_comments.clear()
        default = value if value else "(empty)"
        rows.append(
            {
                "name": name,
                "description": description,
                "default": default,
                "required": "no",
                "section": section,
            }
        )
    return rows


def write_env_reference(path: Path) -> None:
    rows = parse_env_example(ENV_EXAMPLE)
    lines = [
        _banner("Environment variables"),
        "Copy `.env.example` to `.env` (Docker Compose / checkout) or set the same",
        "keys during `keprix setup` (CLI). Never commit `.env`.\n",
        "## Install minimum (CLI and Docker)\n",
        "Set **at least one** of `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`, or",
        "`GEMINI_API_KEY` before first useful agent run.\n",
        "| Variable | Purpose | Default / notes |",
        "| --- | --- | --- |",
        "| `KEPRIX_HOME` | CLI data/config/state home (curl installer) | `$HOME/.keprix` when unset |",
        "| `OPENAI_API_KEY` / `ANTHROPIC_API_KEY` / `GEMINI_API_KEY` | LLM access (need one) | empty; set at least one |",
        "| `AUTH_ENABLED` | Require login for the web UI / API | `true` |",
        "| `KEPRIX_MULTI_USER` | Allow extra accounts beyond the bootstrap admin | `false` |",
        "| `KEPRIX_ALLOWED_ORIGINS` | Browser CORS origins (comma-separated) | `http://localhost:3000` |",
        "| `KEPRIX_INSTANCE_URL` | Public HTTPS origin (links, Stripe returns, CORS companion) | `http://localhost:3000` |",
        "| `KEPRIX_JWT_SECRET` / `KEPRIX_SESSION_SECRET` | Session secrets (required on public hosts) | replace `GENERATE_RANDOM_*` via `scripts/generate-production-env.sh` |",
        "",
        "Docker also needs strong `POSTGRES_PASSWORD` / `REDIS_PASSWORD` (no",
        "`changeme` / placeholder values on a public host). See [Quickstart](../getting-started/quickstart.md)",
        "and [First run](../getting-started/first-run.md).\n",
        "## Full reference (from `.env.example`)\n",
        "Regenerated at docs build time. Empty defaults are optional unless noted",
        "in **Install minimum** above.\n",
        "| Variable | Description | Default | Required |",
        "| --- | --- | --- | --- |",
        "| `KEPRIX_HOME` | CLI data/config/state home (curl installer; see Install minimum) | `$HOME/.keprix` | no |",
    ]
    seen = {"KEPRIX_HOME"}
    for row in rows:
        if row["name"] in seen:
            continue
        seen.add(row["name"])
        desc = row["description"].replace("|", "\\|")
        default = row["default"].replace("|", "\\|")
        lines.append(f"| `{row['name']}` | {desc} | `{default}` | {row['required']} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _openapi_spec() -> dict:
    import tempfile

    docs_data = Path(tempfile.gettempdir()) / "keprix-docs-build-data"
    docs_data.mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("KEPRIX_DATA_DIR", str(docs_data))
    os.environ.setdefault("KEPRIX_HOME", str(docs_data / "home"))
    Path(os.environ["KEPRIX_HOME"]).mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("KEPRIX_DATABASE_URL", "sqlite+aiosqlite:///:memory:")
    os.environ.setdefault("KEPRIX_JWT_SECRET", "docs-build-placeholder-secret")
    os.environ.setdefault("KEPRIX_SESSION_SECRET", "docs-build-placeholder-session")
    sys.path.insert(0, str(ROOT / "src"))
    from keprix.api.server import create_app

    return create_app().openapi()


def write_api_reference(path: Path) -> None:
    spec = _openapi_spec()
    lines = [
        _banner("REST API reference"),
        f"OpenAPI **{spec.get('info', {}).get('version', 'unknown')}** "
        f"({len(spec.get('paths', {}))} paths). "
        "Live spec: `GET /openapi.json` on a running instance.\n",
        "| Method | Path | Summary |",
        "| --- | --- | --- |",
    ]
    for route, methods in sorted(spec.get("paths", {}).items()):
        for method, meta in sorted(methods.items()):
            if method.startswith("x-"):
                continue
            summary = str(meta.get("summary") or meta.get("operationId") or "").replace("|", "\\|")
            lines.append(f"| `{method.upper()}` | `{route}` | {summary} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _cli_subcommands() -> list[str]:
    result = subprocess.run(
        [sys.executable, "-m", "keprix.keprix_cli.main", "--help"],
        cwd=ROOT,
        env={**os.environ, "PYTHONPATH": str(ROOT / "src")},
        capture_output=True,
        text=True,
        check=False,
    )
    text = result.stdout + result.stderr
    match = re.search(r"\{([^}]+)\}", text)
    if not match:
        return []
    return [part.strip() for part in match.group(1).split(",") if part.strip()]


def write_cli_reference(path: Path) -> None:
    env = {**os.environ, "PYTHONPATH": str(ROOT / "src")}
    top = subprocess.run(
        [sys.executable, "-m", "keprix.keprix_cli.main", "--help"],
        cwd=ROOT,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    lines = [
        _banner("CLI command reference"),
        "Generated from `python -m keprix.keprix_cli.main`.\n",
        "## Top-level help\n",
        "```text",
        (top.stdout or top.stderr).strip(),
        "```\n",
        "## Subcommands\n",
        "| Command | Help excerpt |",
        "| --- | --- |",
    ]
    for cmd in _cli_subcommands():
        proc = subprocess.run(
            [sys.executable, "-m", "keprix.keprix_cli.main", cmd, "--help"],
            cwd=ROOT,
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
        excerpt = (proc.stdout or proc.stderr).strip().splitlines()
        summary = ""
        for line in excerpt:
            if line.strip().startswith(cmd):
                summary = line.strip()
                break
        if not summary and len(excerpt) > 1:
            summary = excerpt[1].strip() if excerpt else ""
        summary = summary.replace("|", "\\|")[:200]
        lines.append(f"| `{cmd}` | {summary or 'See CLI help'} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_changelog(path: Path) -> None:
    body = CHANGELOG.read_text(encoding="utf-8") if CHANGELOG.exists() else "_No CHANGELOG.md found._\n"
    if body.startswith("# Changelog"):
        body = body.split("\n", 1)[1].lstrip("\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# Changelog\n\n" + body, encoding="utf-8")


def write_license(path: Path) -> None:
    body = LICENSE.read_text(encoding="utf-8") if LICENSE.exists() else "_No LICENSE file found._\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# License\n\n```text\n" + body.strip() + "\n```\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Keprix documentation reference pages")
    parser.add_argument("--docs-dir", type=Path, default=DOCS)
    parser.add_argument(
        "--only",
        choices=("changelog", "license", "env", "api", "cli", "all"),
        default="all",
        help="Generate a single reference page (changelog avoids importing the API app)",
    )
    args = parser.parse_args()
    docs = args.docs_dir
    target = args.only

    if target in ("all", "env"):
        write_env_reference(docs / "configuration" / "environment-variables.md")
    if target in ("all", "api"):
        write_api_reference(docs / "reference" / "api.md")
    if target in ("all", "cli"):
        write_cli_reference(docs / "reference" / "cli.md")
    if target in ("all", "changelog"):
        write_changelog(docs / "reference" / "changelog.md")
    if target in ("all", "license"):
        write_license(docs / "reference" / "license.md")
    print(f"Generated reference pages under {docs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
