"""Runtime transport protocol for the Keprix TUI."""

from __future__ import annotations

from typing import Any, AsyncIterator, Protocol, runtime_checkable

from keprix.tui.client import ModelItem, RegistryItem, SessionItem, TuiConfig
from keprix.tui.runtime_transport.events import RuntimeTransportEvent


@runtime_checkable
class RuntimeTransport(Protocol):
    mode: str

    async def health(self) -> bool: ...

    async def ensure_ready_session(self, session_id: str | None) -> str: ...

    async def list_sessions(self) -> list[SessionItem]: ...

    async def create_session(self, title: str = "New conversation") -> SessionItem: ...

    async def get_messages(self, session_id: str) -> tuple[str, list[dict[str, Any]]]: ...

    async def list_models(self) -> list[ModelItem]: ...

    async def send_message_stream(self, session_id: str, content: str) -> AsyncIterator[RuntimeTransportEvent]: ...

    async def interrupt(self, session_id: str, *, keep_queue: bool = False) -> None: ...

    async def steer(self, session_id: str, text: str) -> int: ...

    async def command_complete(self, prefix: str, *, session_id: str = "") -> list[str]: ...

    async def command_dispatch(self, name: str, arg: str, *, session_id: str = "") -> dict[str, Any]: ...

    async def list_skills(self) -> list[RegistryItem]: ...

    async def list_plugins(self) -> list[RegistryItem]: ...

    async def get_tui_config(self) -> TuiConfig: ...


__all__ = ["RuntimeTransport"]
