"""AI transparency: labels, consent gate, generation log, compliance report."""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import pytest

from keprix.transparency.consent_gate import ConsentGate, ConsentRequiredError
from keprix.transparency.generation_log import GenerationLogStore, ImmutableLogError
from keprix.transparency.hashing import sha256_text
from keprix.transparency.labels import LABEL_MARKER, SgiLabeler
from keprix.transparency.pipeline import finalize_ai_output


def test_sha256_hashing():
    assert sha256_text("hello") == hashlib.sha256(b"hello").hexdigest()


def test_disclosure_locales():
    labeler = SgiLabeler()
    for locale in ("en", "fr", "de", "es"):
        text = labeler.get_disclosure_text(locale)
        assert text
        assert labeler.is_label_removable() is False
    labeled = labeler.label_output("Hello world", "text", locale="en")
    assert LABEL_MARKER in labeled["label"]["marker"]
    assert labeled["label"]["removable"] is False
    assert "AI-generated content" in labeled["labeled_output"]
    code = labeler.label_output("print(1)", "code")
    assert "Generated by AI" in code["labeled_output"]


def test_generation_log_append_only_and_report(tmp_path: Path):
    store = GenerationLogStore(sqlite_path=tmp_path / "gen.db")
    row = store.log_generation(
        input_payload="prompt",
        output_payload="answer",
        model_name="test-model",
        user_id="u1",
        content_type="text",
        feature_endpoint="chat",
        session_id="s1",
    )
    assert row["input_hash"] == sha256_text("prompt")
    assert row["output_hash"] == sha256_text("answer")
    with pytest.raises(ImmutableLogError):
        store.update_entry(row["log_id"])
    with pytest.raises(ImmutableLogError):
        store.delete_entry(row["log_id"])

    day = row["timestamp"][:10]
    report = store.generate_compliance_report(day)
    assert report["entry_count"] == 1
    assert report["entries"][0]["log_id"] == row["log_id"]
    assert report["signature"]["value"]
    assert report["content_hash"]


def test_migration_revokes_update_delete():
    migration = (
        Path(__file__).resolve().parents[2]
        / "migrations"
        / "versions"
        / "038_ai_transparency_generation_log.py"
    )
    source = migration.read_text(encoding="utf-8")
    assert "REVOKE UPDATE, DELETE ON generation_log" in source
    assert "forbid_generation_log_mutation" in source
    assert "generation_log_no_update" in source
    assert "app_user" in source
    assert "keprix" in source


def test_consent_granular_and_withdrawal(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv("KEPRIX_AI_CONSENT_REQUIRED", "1")
    gate = ConsentGate(base_dir=tmp_path)
    with pytest.raises(ConsentRequiredError):
        gate.require_consent("u1", "text_generation")
    with pytest.raises(ValueError):
        gate.record_consent("u1", "text_generation", action="granted", affirmative=False)

    gate.record_consent("u1", "text_generation", action="granted", affirmative=True)
    assert gate.require_consent("u1", "text_generation")["ok"] is True
    # Image consent is separate
    with pytest.raises(ConsentRequiredError):
        gate.require_consent("u1", "image_generation")

    gate.record_consent("u1", "text_generation", action="withdrawn", affirmative=True)
    with pytest.raises(ConsentRequiredError):
        gate.require_consent("u1", "text_generation")
    history = gate.get_consent_status("u1")["history"]
    assert len(history) == 2
    assert history[-1]["action"] == "withdrawn"
    with pytest.raises(RuntimeError):
        gate.delete_consent("u1", "text_generation")


def test_integration_consent_log_label(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv("KEPRIX_AI_CONSENT_REQUIRED", "1")
    monkeypatch.setenv("KEPRIX_AI_GENERATION_LOG_ENABLED", "1")
    monkeypatch.setenv("KEPRIX_AI_LABELING_ENABLED", "1")
    gate = ConsentGate(base_dir=tmp_path / "consent")
    store = GenerationLogStore(sqlite_path=tmp_path / "gen.db")

    # Patch singletons used by pipeline
    monkeypatch.setattr("keprix.transparency.pipeline.get_consent_gate", lambda: gate)
    monkeypatch.setattr("keprix.transparency.pipeline.get_generation_log_store", lambda: store)

    with pytest.raises(ConsentRequiredError):
        finalize_ai_output(
            input_payload="hi",
            output_payload="there",
            model_name="m1",
            user_id="u9",
        )

    gate.record_consent("u9", "text_generation", action="granted", affirmative=True)
    result = finalize_ai_output(
        input_payload="hi",
        output_payload="there",
        model_name="m1",
        user_id="u9",
        feature_endpoint="chat",
    )
    assert result["log"]["input_hash"] == sha256_text("hi")
    assert "AI-generated content" in result["labeled_output"]
    assert result["label"]["removable"] is False
    day = result["log"]["timestamp"][:10]
    report = store.generate_compliance_report(day)
    assert report["entry_count"] >= 1


def test_frontend_disclosure_non_removable():
    component = (
        Path(__file__).resolve().parents[2]
        / "frontend"
        / "src"
        / "components"
        / "transparency"
        / "AiGeneratedDisclosure.tsx"
    )
    source = component.read_text(encoding="utf-8")
    assert 'data-sgi-removable="false"' in source
    assert "isDisclosureRemovable" in source
    assert "return false" in source
    assert "onClose" not in source and "onDismiss" not in source
