"""Setup wizard for first-run configuration."""

from __future__ import annotations

import json
import re
import secrets
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from keprix.config.constants import PRODUCT_VERSION
from keprix.installer.paths import get_env_file, get_install_root, get_repo_root, get_state_file

PromptFn = Callable[[str, str], str]

REQUIRED_ENV_KEYS = (
    "KEPRIX_VERSION",
    "KEPRIX_INSTANCE_NAME",
    "KEPRIX_ADMIN_PASSWORD",
    "KEPRIX_JWT_SECRET",
    "KEPRIX_SESSION_SECRET",
    "KEPRIX_IP_HASH_SALT",
    "POSTGRES_PASSWORD",
    "REDIS_PASSWORD",
    "BACKEND_PORT",
    "FRONTEND_PORT",
)


@dataclass
class WizardAnswers:
    is_developer_owner: bool = False
    instance_name: str = "keprix"
    external_domain: str = ""
    enable_ssl: bool = False
    admin_email: str = ""
    llm_api_key: str = ""
    llm_provider: str = ""


@dataclass
class WizardResult:
    env_path: Path
    admin_password: str
    values: dict[str, str] = field(default_factory=dict)
    developer_identity_created: bool = False


def _default_prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    return input(f"{label}{suffix}: ").strip() or default


def _yes_no(prompt: str, default: bool = False) -> bool:
    default_label = "Y/n" if default else "y/N"
    answer = input(f"{prompt} ({default_label}): ").strip().lower()
    if not answer:
        return default
    return answer in {"y", "yes"}


def generate_secrets() -> dict[str, str]:
    return {
        "KEPRIX_JWT_SECRET": secrets.token_urlsafe(48),
        "KEPRIX_SESSION_SECRET": secrets.token_urlsafe(48),
        "KEPRIX_IP_HASH_SALT": secrets.token_hex(32),
        "POSTGRES_PASSWORD": secrets.token_urlsafe(24),
        "REDIS_PASSWORD": secrets.token_urlsafe(24),
        "KEPRIX_ADMIN_PASSWORD": secrets.token_urlsafe(16),
        "KEPRIX_VAULT_KEY": secrets.token_urlsafe(32),
    }


def _parse_env_example(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by keprix setup wizard",
        f"# {datetime.now(timezone.utc).isoformat()}",
        "",
    ]
    for key in sorted(values.keys()):
        lines.append(f"{key}={values[key]}")
    return "\n".join(lines) + "\n"


def _detect_llm_provider(api_key: str) -> str:
    if api_key.startswith("sk-ant-"):
        return "anthropic"
    if api_key.startswith("sk-"):
        return "openai"
    if api_key.startswith("gsk_"):
        return "groq"
    return "openai"


def run_wizard(
    *,
    answers: WizardAnswers | None = None,
    interactive: bool = True,
    prompt_fn: PromptFn | None = None,
    env_out: Path | None = None,
    env_example: Path | None = None,
    create_developer_identity: Callable[..., dict[str, Any]] | None = None,
) -> WizardResult:
    """Run setup wizard and write .env. Non-interactive when answers is provided."""
    prompt = prompt_fn or _default_prompt
    resolved_answers = answers or WizardAnswers()

    if interactive and answers is None:
        resolved_answers.is_developer_owner = _yes_no(
            "Are you the owner or developer of this installation?",
            default=False,
        )
        resolved_answers.instance_name = prompt("Installation name", "keprix")
        resolved_answers.external_domain = prompt("External domain (blank for localhost)", "")
        if resolved_answers.external_domain:
            resolved_answers.enable_ssl = _yes_no("Enable SSL with certbot?", default=True)
        resolved_answers.admin_email = prompt("Admin email", "")
        resolved_answers.llm_api_key = prompt(
            "LLM provider API key (press Enter to skip and configure later)",
            "",
        )

    secrets_map = generate_secrets()
    admin_password = secrets_map.pop("KEPRIX_ADMIN_PASSWORD")

    example_path = env_example or (get_repo_root() / ".env.example")
    env_values = _parse_env_example(example_path)

    env_values.update(secrets_map)
    env_values["KEPRIX_VERSION"] = PRODUCT_VERSION
    env_values["KEPRIX_INSTANCE_NAME"] = resolved_answers.instance_name
    env_values["KEPRIX_ADMIN_PASSWORD"] = admin_password
    env_values["BACKEND_PORT"] = env_values.get("BACKEND_PORT", "3333")
    env_values["FRONTEND_PORT"] = env_values.get("FRONTEND_PORT", "3000")
    env_values["KEPRIX_DATABASE_URL"] = (
        f"postgresql+asyncpg://keprix:{env_values['POSTGRES_PASSWORD']}@postgres:5432/keprix"
    )
    env_values["KEPRIX_REDIS_URL"] = f"redis://:{env_values['REDIS_PASSWORD']}@redis:6379"

    if resolved_answers.external_domain:
        env_values["KEPRIX_EXTERNAL_DOMAIN"] = resolved_answers.external_domain
        env_values["KEPRIX_ALLOWED_ORIGINS"] = f"https://{resolved_answers.external_domain}"
        if resolved_answers.enable_ssl:
            env_values["KEPRIX_ENABLE_SSL"] = "true"
    else:
        port = env_values["FRONTEND_PORT"]
        env_values["KEPRIX_ALLOWED_ORIGINS"] = f"http://localhost:{port}"

    if resolved_answers.admin_email:
        env_values["KEPRIX_ADMIN_EMAIL"] = resolved_answers.admin_email

    if resolved_answers.llm_api_key:
        provider = resolved_answers.llm_provider or _detect_llm_provider(resolved_answers.llm_api_key)
        key_name = {
            "openai": "OPENAI_API_KEY",
            "anthropic": "ANTHROPIC_API_KEY",
            "groq": "GROQ_API_KEY",
        }.get(provider, "OPENAI_API_KEY")
        env_values[key_name] = resolved_answers.llm_api_key
        env_values["KEPRIX_DEFAULT_PROVIDER"] = provider

    out_path = env_out or get_env_file()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_render_env(env_values), encoding="utf-8")

    identity_created = False
    if resolved_answers.is_developer_owner and create_developer_identity is not None:
        create_developer_identity(force=False)
        identity_created = True
        env_values["KEPRIX_DEVELOPER_MODE"] = "true"

    state = {
        "version": PRODUCT_VERSION,
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "instance_name": resolved_answers.instance_name,
        "env_file": str(out_path),
    }
    state_path = get_state_file()
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")

    return WizardResult(
        env_path=out_path,
        admin_password=admin_password,
        values=env_values,
        developer_identity_created=identity_created,
    )


def validate_env_file(path: Path) -> list[str]:
    """Return missing required keys for acceptance tests."""
    if not path.exists():
        return list(REQUIRED_ENV_KEYS)
    content = path.read_text(encoding="utf-8")
    missing = []
    for key in REQUIRED_ENV_KEYS:
        if not re.search(rf"^{re.escape(key)}=.+$", content, flags=re.MULTILINE):
            missing.append(key)
    return missing
