"""Cover page and signatory block HTML generation for keprix document exports."""

from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any


def generate_cover_html(
    *,
    title: str,
    document_type: str = "",
    version: str = "",
    prepared_by: str = "",
    classification: str = "",
    document_id: str = "",
) -> str:
    """Return an HTML cover page string for prepending to a document export."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    def _row(label: str, value: str) -> str:
        if not value:
            return ""
        return (
            f'<tr><td class="cover-label">{html.escape(label)}</td>'
            f'<td class="cover-value">{html.escape(value)}</td></tr>'
        )

    rows = "".join([
        _row("Document Type", document_type),
        _row("Version", version),
        _row("Prepared by", prepared_by),
        _row("Generated on", now),
        _row("Document ID", document_id),
        _row("Classification", classification),
    ])

    return f"""<div class="cover-page">
  <h1 class="cover-title">{html.escape(title)}</h1>
  <hr class="cover-rule"/>
  <table class="cover-meta">
    {rows}
  </table>
  <hr class="cover-rule cover-rule-bottom"/>
</div>
<style>
  .cover-page {{ page-break-after: always; padding: 48pt 0; }}
  .cover-title {{ font-size: 24pt; margin-bottom: 12pt; }}
  .cover-rule {{ border: none; border-top: 1px solid #333; margin: 8pt 0; }}
  .cover-rule-bottom {{ margin-top: 24pt; }}
  .cover-meta {{ border-collapse: collapse; width: 100%; margin-top: 16pt; }}
  .cover-label {{ font-weight: bold; padding: 4pt 8pt 4pt 0; width: 35%; vertical-align: top; }}
  .cover-value {{ padding: 4pt 0; }}
</style>
"""


def generate_signatory_html(data: dict[str, Any]) -> str:
    """Return an HTML signatory block string for appending to a document export."""
    reviewer = html.escape(str(data.get("reviewer_name", "")))
    role = html.escape(str(data.get("reviewer_role", "")))
    decision = html.escape(str(data.get("decision", "")))
    timestamp = html.escape(str(data.get("timestamp", "")))
    notes = html.escape(str(data.get("notes", "")))

    notes_html = f'<p class="signatory-notes">Notes: {notes}</p>' if notes else ""
    decision_class = {
        "approved": "decision-approved",
        "rejected": "decision-rejected",
        "deferred": "decision-deferred",
    }.get(decision.lower(), "")

    return f"""<section class="signatory-block">
  <h3>Review Sign-off</h3>
  <table class="signatory-table">
    <tr><td>Reviewer</td><td>{reviewer}</td></tr>
    <tr><td>Role</td><td>{role}</td></tr>
    <tr><td>Decision</td><td class="{decision_class}">{decision}</td></tr>
    <tr><td>Timestamp</td><td>{timestamp}</td></tr>
  </table>
  {notes_html}
  <p class="signatory-legal">This record was generated by keprix review gateway. The decision was submitted via a cryptographically signed single-use link by the named reviewer.</p>
</section>
<style>
  .signatory-block {{ margin-top: 30pt; border-top: 2px solid #333; padding-top: 12pt; }}
  .signatory-table {{ border-collapse: collapse; width: 100%; }}
  .signatory-table td {{ padding: 4pt 8pt 4pt 0; }}
  .signatory-legal {{ font-size: 8pt; color: #666; margin-top: 8pt; }}
  .decision-approved {{ color: #1a7a1a; font-weight: bold; }}
  .decision-rejected {{ color: #b00; font-weight: bold; }}
  .decision-deferred {{ color: #a06000; font-weight: bold; }}
</style>
"""
