"""Visible, non-removable SGI disclosure labels for AI-generated outputs."""

from __future__ import annotations

from typing import Any, Literal

ContentType = Literal["text", "image", "code", "audio", "video"]

# Locale -> visible disclosure shown to end users (not buryable footnotes).
DISCLOSURE_TEXT: dict[str, str] = {
    "en": "AI-generated content",
    "fr": "Contenu generee par l'IA",
    "de": "KI-generierte Inhalte",
    "es": "Contenido generado por IA",
}

# Stable marker used to detect / refuse stripping labels in application code.
LABEL_MARKER = "keprix-sgi-disclosure"
NON_REMOVABLE = True


class SgiLabeler:
    """Annotate AI outputs with EU AI Act SGI disclosures."""

    def get_disclosure_text(self, locale: str = "en") -> str:
        key = (locale or "en").strip().lower().split("-")[0]
        return DISCLOSURE_TEXT.get(key) or DISCLOSURE_TEXT["en"]

    def is_label_removable(self, label: dict[str, Any] | str | None = None) -> bool:
        """Labels are never removable by end users (UI + API contract)."""
        _ = label
        return False

    def label_output(
        self,
        output: str | bytes | dict[str, Any] | None,
        content_type: ContentType = "text",
        *,
        locale: str = "en",
        model_name: str | None = None,
    ) -> dict[str, Any]:
        disclosure = self.get_disclosure_text(locale)
        meta = {
            "X-AI-Generated": "true",
            "X-SGI-Disclosure": disclosure,
            "X-SGI-Marker": LABEL_MARKER,
            "X-SGI-Removable": "false",
            "content_type": content_type,
            "locale": locale,
            "model_name": model_name,
            "non_removable": True,
        }

        if content_type == "text":
            body = "" if output is None else str(output)
            if LABEL_MARKER in body or body.lstrip().startswith("AI-generated content"):
                labeled = body
            else:
                labeled = f"[{disclosure}]\n\n{body}"
            return {
                "labeled_output": labeled,
                "disclosure": disclosure,
                "label": {
                    "kind": "text_prefix",
                    "text": disclosure,
                    "marker": LABEL_MARKER,
                    "removable": False,
                },
                "metadata": meta,
            }

        if content_type == "code":
            body = "" if output is None else str(output)
            header = f"// Generated by AI; verify before use ({disclosure})\n// {LABEL_MARKER}\n"
            if LABEL_MARKER in body:
                labeled = body
            else:
                labeled = header + body
            return {
                "labeled_output": labeled,
                "disclosure": disclosure,
                "label": {
                    "kind": "code_comment",
                    "text": header.strip(),
                    "marker": LABEL_MARKER,
                    "removable": False,
                },
                "metadata": meta,
            }

        if content_type == "image":
            # Overlay is applied at the UI/renderer; we attach durable metadata.
            return {
                "labeled_output": output,
                "disclosure": disclosure,
                "label": {
                    "kind": "image_watermark",
                    "text": disclosure,
                    "watermark": True,
                    "marker": LABEL_MARKER,
                    "removable": False,
                },
                "metadata": meta,
            }

        # audio / video: pre-roll disclosure + metadata
        return {
            "labeled_output": output,
            "disclosure": disclosure,
            "label": {
                "kind": "av_preroll",
                "text": disclosure,
                "preroll": True,
                "marker": LABEL_MARKER,
                "removable": False,
            },
            "metadata": meta,
        }
